### ISSUE TITLE
Period facet

### ISSUE THREAD

**Issue by edgartdata** [ycba-cia/blacklight-collections2#114]
@flapka @KraigBinkowski How feasible would it be for your 2 collections to provide finessed data for the Period facet? There are fewer than 30 of such records overall (some of them are from the art collections and I will deal with those).

**Comment by flapka** [comment]
@edgartdata @KraigBinkowski @yulgit1 

The current mapping for this data is wrong. It appears to be grabbing from $z of *subject* headings, which often results in bad data. For example, a 19th century book *about* something in the 16th century will give us Period data of 16th century -- which isn't the intent of the Period facet, right?

I think it would be relatively trivial to derive Period information from the value in earliestDate (and perhaps latestDate). E.g.: if earliest date is between 1801 and 1900, Period = "19th century" and so on.

I think Period data derived in this manner would work relatively well for RB material. I'll leave it to Kraig to chime in on whether it'd be desirable for Ref material.

**Comment by KraigBinkowski** [comment]
As far as ref goes, I think it would be most beneficial if Period mapping does indeed give us results that are **about** the different periods and not books that are **from** a certain date. This may be be the opposite of Rare Books' desires as Francis describes it.

**Comment by flapka** [comment]
I understand Kraig's POV for Ref material. My concern is that it might be confusing (to users) if the data sometimes means that the object is *of* a certain period, and sometimes means *about* a certain period.

**Comment by KraigBinkowski** [comment]
I see how that could be confusing -- in that case, I would be in favor of Ref not using the Period facet at all (is this possible?). It is much more important to me that subject searching is effective.

**Comment by edgartdata** [comment]
@flapka @KraigBinkowski The Period facet intends to reference the century in which the item (painting, manuscript or book) was created. For example, if a book is about the oeuvre of a 17th century artist but is published in 2018 then its Period value in the Period facet would be 21st century.
I have no problem with the Ref Library's data not coming through here if it is problematic with its data.

**Comment by edgartdata** [comment]
Kraig is okay with taking the Reference Library collection out of the Period facet.

**Comment by edgartdata** [comment]
@yulgit1 Can we create a new index field for a new facet called Subject Period (tbd) for all records coming from MARC. Answer: yes. @flapka to detail what index field to grab for what collection and what facet.
@EdwardTown1 We may want to think about implementing this for the art collections?

**Comment by flapka** [comment]
The current XSLT template for "era" (lines 3097-3124 of marc-preblacklight-ycba.xsl) should instead be applied to the new field we've proposed, Subject Period. 

Then, for mapping MARC data to Period (era), we should create a new template that derives a century value based on the earliest date value. So:

For any item in the bacrb record set, when
earliest date is between 1201 and 1300, "13th century"
earliest date is between 1301 and 1400, "14th century"
...
earliest date is between 2001 and 2100, "21st century"

If the index allows repeatable values for Period -- and it appears to do so -- then we'd also want to run the same procedure on latest dates.

**Comment by KraigBinkowski** [comment]
Just confirming that the proposed new facet field: Subject Period, is to include Reference material and drawing from the Marc 6xx (600, 610, 650) fields, subfield y. 
For the existing Period facet, no Reference materials will be harvested.

**Comment by flapka** [comment]
@KraigBinkowski Correct.

**Comment by flapka** [comment]
Issue 1 (for the Period facet): To harmonize data between art and library collections, I think that the 'C' in "Century" should be made lowercase, i.e. "century"

**Comment by flapka** [comment]
Issue 2 (for the Period facet): "21th Century" should instead be "21st century"

**Comment by yulgit1** [comment]
Updated the mappings and tested a few.  Full reindexing scheduled for Saturday 4/6.

https://git.yale.edu/ermadmix/camel_collections2/commit/96128e20245ec753c62869e2f379d9c7960d185b (this link might not be public)

**Comment by flapka** [comment]
Link appears not to be public, but we can return after reindexing.

**Comment by yulgit1** [comment]
Reindexed ok over weekend, (w/ lowercase century for Marc records, and 21'st').  Still a few capital 'C' centuries in museum objects.  Can these be fixed in TMS data @edgartdata?

**Comment by flapka** [comment]
@yulgit1 Looks like we're very close on the Period facet.

As for the *Subject Period* facet, there is a fair amount of dirty data (e.g. "[184-?]"). We could make this a lot cleaner by modifying the XSLT. 

In the template for "era" in the XSLT, I suggest removing tags 690 692 and 693. Doing so would remove most (or all) of the dirty data and retain the good data.

**Comment by yulgit1** [comment]
resolved:
https://git.yale.edu/ermadmix/ycba_xslts/commit/3a42ef2ca018c0ad0c6989419a7dc94cf528c115

(template 'era' still used for subject_period_ss field)

will show up after indexing

**Comment by edgartdata** [comment]
@yulgit1 @flapka 
There are still pockets of art collection century values that have capital C: 9 P&D in 20th Century, and 3 in 18th Century.
@yulgit1 I wonder why the transform you did on the other art collection upper case century values did not apply to these? For the record, I would rather not have to change the cataloguing practices nor the stylistic guidelines if possible. 
Also 19e siècle is giving me an error so I can't see what collection it is in.
![image](https://user-images.githubusercontent.com/4093644/55813451-c6f6f100-5aba-11e9-8567-d46eef3283ff.png)

**Comment by flapka** [comment]
The 19e siecle entry is associated with a Ref Library record that no longer exists (#11221582). 

Is this a sign of a larger problem: Why does the record still appear in search results when it has been removed from Orbis?

**Comment by KraigBinkowski** [comment]
Suppressed records showing in searches?

**Comment by edgartdata** [comment]
@edgartdata to fix the capitalized century values for the art collection.

**Comment by edgartdata** [comment]
@flapka to check the harvester to see if there is a flag for deleted records that Eric can filter on.

**Comment by edgartdata** [comment]
@yulgit1 I changed to lower case the 9 '20th Century' in TMS on 3/11 per the TMS audit trail but they still show up capitalized in Blacklight.
The 3 '18th Century' were capitalized in TMS until today. I just fixed them.
Is the Blacklight data refresh process partial? or maybe these changes are too small to be picked up?

**Comment by flapka** [comment]
> @flapka to check the harvester to see if there is a flag for deleted records that Eric can filter on.

@edgartdata @yulgit1 @KraigBinkowski 

Here's an example of what the OAI feed returns when we it asks for a record that has been deleted from Voyager/Orbis:

![image](https://user-images.githubusercontent.com/7634899/56159242-2d37b400-5f92-11e9-8ddc-a6fbd93537ab.png)

The OAI feed gives the same when a record has been *suppressed* in Voyager/Orbis -- i.e., when we want to keep the record but keep it in invisible to the public.

Two questions:

1. If the above response is insufficient to prompt an update to the YCBA catalog data, would the issue be resolved by periodically wiping all data from the YCBA catalog and reharvesting? (I acknowledge that this method may be undesirable for reasons opaque to me.)

2. Alternatively, could a script periodically cycle through every RB/REF/IA item in the YCBA catalog -- querying the OAI feed to see if it gets this response? When it does, delete from the YCBA catalog?

**Comment by yulgit1** [comment]
(1) is undesirable because it might cut into 100% uptime, I think we should go with (2).

**Comment by edgartdata** [comment]
Are these records deletes & omissions time sensitive? My guess is that we probably don't want to let too much time go by before they disappear from Blacklight.

**Comment by flapka** [comment]
@yulgit1 Makes sense to go with (2), if you can envision a script that that would do the job.

@edgartdata Yes, we wouldn't want the obsolete (deleted) records to remain in Blacklight for long: no more than 1 week is preferable; no more than 1 day would be ideal.

**Comment by yulgit1** [comment]
I started coding (2), but am concerned 1) it's making 50k calls to harvester to check,2) these 50k are slow (2-3 second), taking like 7-8 hours to complete (which would run on a daily basis).

Alternatively, what do you think about using a lightweight web interface where you could enter orbis IDs, or TMS IDs to be deleted manually from the index? 

@flapka, @edgartdata, @KraigBinkowski  Let me know.

**Comment by flapka** [comment]
@yulgit1 @edgartdata @KraigBinkowski I think such a web interface would work well enough. Perhaps we could use it in combination with infrequent data purges/reharvests (1, 2, or 4 times per year) -- to account for human error (when we forget to register deletions in the web interface).

**Comment by edgartdata** [comment]
I would be super happy with a web interface giving me more control over deletes. 3-4 scheduled data purges/reharvests a year seem like a reasonable schedule.

**Comment by edgartdata** [comment]
Eric demonstrated the web interface that he built to allow collections to delete records from BlackLight.

**Comment by edgartdata** [comment]
@yulgit1  I have a mechanism in TMS to filter out records that should not be published online but your injonction begs the question: if a record is deleted by mistake and needs to be reinstated, what is the process for that?

**Comment by flapka** [comment]
@yulgit1 @edgartdata 

I notice today that some wonky values have crept back in to the subject period facet, as if it were mapping incorrectly -- whereas before it had been rather perfect (?).  Do we know the cause?

**Comment by yulgit1** [comment]
@flapka There has not been any change since the removal of 690,692,693:
https://git.yale.edu/ermadmix/ycba_xslts/commit/3a42ef2ca018c0ad0c6989419a7dc94cf528c115

One example of wonky subject_period_ss:[18--] is coming from a 655y which is still mapped to subject_period_ss
https://libapp.library.yale.edu/OAI_BAC/src/OAIOrbisTool.jsp?verb=GetRecord&identifier=oai:orbis.library.yale.edu:3182886&metadataPrefix=marc21

**Comment by flapka** [comment]
@yulgit1 @edgartdata Thanks Eric. You've helped me realize that the XSLT needs a slight tweak, to remove 655 from the tags mapped to subject_period. 

(The 655 contains data about what an object *is* instead of what it is *about*, so the data is out of scope for subject period.)

**Comment by yulgit1** [comment]
addressed:
https://git.yale.edu/ermadmix/ycba_xslts/commit/e42e5797b608b3cd1d610c97278af8bf2d5c98cc

Will appear after next reindexing (no reindexing this weekend due to TMS upgrade).

**Comment by yulgit1** [comment]
@KraigBinkowski @flapka 
Other than long tail outlier cleanup in the Marc for the Subject Period facet, is this closable?

**Comment by flapka** [comment]
Yes, I think so.
