### ISSUE TITLE
people represented facet

### ISSUE THREAD

**Issue by yulgit1** [ycba-cia/blacklight-collections2#47]
add 

People Represented: add a new facet for them. It maps to <lido:subjectConcept> when lido:type="subjectActor"

**Comment by yulgit1** [comment]
there is 'topic_subjectActor_facet' that maps to:

lido:objectRelationWrap/lido:subjectWrap/lido:subjectSet/lido:subject[@lido:type='description']/lido:subjectActor/lido:displayActor
            
@edgartdata  does that suffice?

**Comment by yulgit1** [comment]
**from a test implementation of topic_subjectActor_facet:**
Shakespeare, William (1564–1616), playwright and poet	1,008
Jesus Christ (7-2 BC/BCE to 30-36 AD/CE)	105
Garrick, David (1717–1779), actor and playwright	50
Hockney, David (born 1937), English painter, printmaker, and photographer	46
Cupid	43
Venus	42
Jones, Inigo (1573–1652), architect and theatre designer	30
Sir John Falstaff	25
Job	23
Russell, Lord John, 1st Earl Russell of Kingston Russell (1792-1878), politician/statesman	22
Fox, George (1624–1691), a founder of the Religious Society of Friends (Quakers)	21
saint	21
Adonis	20
Reynolds, Sir Joshua (1723–1792), portrait and history painter and art theorist	20
Apollo	19
West, Benjamin (1738–1820), American history painter active in Britain	18
William Hogarth	18
Jack Sheppard	17
Paul, the Apostle, St. (c. AD 5–c. AD 67)	17
The Virgin Mary	17
Keeler, Christine (1942-), British model	16
Wellesley, Arthur, first duke of Wellington (1769–1852), army officer and prime minister	16
Abington, Frances (1737–1815), actress	15
Hamilton, Emma, Lady Hamilton (bap. 1765, d. 1815), social celebrity and artist's model	15
demons	15
Cook, Peter (1937–1995), humorist and entertainer	14
Cordelia (character in King Lear)	14
Macbeth (character in The Tragedy of Macbeth)	14
Moore, Dudley Stuart John (1935–2002), actor, musician, and composer	14
Othello (character in Othello, the Moor of Venice)	14
Satan	14
Eve	13
Juliet (character in Romeo and Juliet)	13
The Three Witches (characters in Macbeth)	13
Diana	12
King Lear (character in King Lear)	12
Lady Macbeth (character in Macbeth)	12
Miranda (character in The Tempest)	12
Victoria (1819–1901), queen of the United Kingdom of Great Britain and Ireland, and empress of India	12
Whistler, James Abbott McNeill (1834–1903), painter and printmaker	12
Bacchus	11
Dyck, Sir Anthony Van (1599–1641), painter and etcher	11
Frost, David (1939-2013), journalist, comedian, writer, media personality, and daytime TV game show host	11
George III (1738–1820), king of the United Kingdom of Great Britain and Ireland, and king of Hanover	11
Hercules	11
Mary Magdalene, Saint (early 1st c. AD – mid-late 1st c. AD)	11
Peter, the Apostle, St. (ca. 1 BC - ca. 68 AD)	11
Prospero (character in The Tempest)	11
Bentinck, Lord George (1802-1848), politician/statesman, athlete/sportsman	10
Christ	10
Cosway, Richard (bap. 1742, d. 1821), artist and collector	10
Finney, Albert (born 1936), actor	10
Fox, Charles James (1749–1806), politician	10
Kauffman, Angelica (1741–1807), history and portrait painter	10
Mary	10
Ophelia (character in Hamlet)	10
Peter, Henry, 1st Baron Brougham and Vaux (1778–1868), politician/statesman	10
Zoffany, Johan Joseph (1733–1810), portrait painter	10
saints	10
Banquo (character in Macbeth)	9
Desdemona (character in Othello)	9
Hamlet, Prince of Denmark	9
Henry VIII (1491–1547), king of England and Ireland	9
Mary [Mary Stewart] (1542–1587), queen of Scots	9
Miller, Jonathan Wolfe (born 1934), stage director and author	9
Nollekens, Joseph (1737–1823), sculptor	9
O'Connell, Daniel (1775–1847), Irish nationalist leader	9
Orton, John Kingsley “Joe” (1933–1967), playwright	9
Telemachus	9
characters	9
Adam	8
Ariel (character in The Tempest)	8
Bartolozzi, Francesco (1728–1815), engraver	8
Bennett, Alan (born 1934), playwright, screenwriter, actor, and author	8
Lady Hamilton	8
Malvolio (character in Twelfth Night)	8
Northcote, James (1746–1831), artist and author	8
Pope, Alexander (1688–1744), poet	8
Sandby, Paul (bap. 1731, d. 1809), painter and engraver	8
Sandby, Thomas (bap. 1723, d. 1798), architect and draughtsman	8
Albert (1819–1861), prince consort, consort of Queen Victoria	7
Burke, Edmund (1729/30–1797), politician and author	7
Cipriani, Giovanni Battista (1727–1785), decorative painter and draughtsman	7
Disraeli, Benjamin, 1st Earl of Beaconsfield (1804-1881), politician/statesman, author/poet	7
Elizabeth I (1533-1603), queen of England and Ireland	7
Epstein, Brian Samuel (1934–1967), popular music entrepreneur and retailer	7
George IV (1762–1830), king of the United Kingdom of Great Britain and Ireland, and king of Hanover	7
Hayman, Francis (1707/8–1776), painter, engraver, and book illustrator	7
James VI and I (1566–1625), king of Scotland, England, and Ireland	7
John the Evangelist, Saint (c. 1–c. 100 AD)	7
Jupiter	7
Kneller, Sir Godfrey, baronet (1646–1723), history and portrait painter	7
Locke, John (1632–1704), philosopher	7
Madonna	7
Mellon, Paul (1907–1999), philanthropist and art collector	7
Minerva	7
Morley, Lewis (1925-2013), photographer	7
Olivier, Laurence Kerr, Baron Olivier (1907–1989), actor and director	7
Siddons (née Kemble), Sarah (1755–1831), actress	7
Stubbs, George (1724–1806), painter, engraver, and anatomist	7

**Comment by edgartdata** [comment]
Looks good to me.
@flapka and Kraig: Would your collections have metadata to contribute to this facet?

**Comment by flapka** [comment]
@edgartdata : When library descriptions record a person as subject of the item (MARC 600), it may mean that the person is the subject of the text or that the person is visually depicted (sometimes both). In a fair number of library records, the 600 field will include the subdivision 'Portraits' (e.g. "Mellon, Paul -- Portraits"). I think it would be sensible to map such headings to the people represented facet (discarding the word "Portraits" when we do).

**Comment by edgartdata** [comment]
@flapka Sounds great! 
Does that mean that we also need to harmonize names for this facet? 
That might be more difficult for the art collections as there are many people who don't have authority files. However, whenever we can we do add ULAN URIs to the names of sitters (organized in the TMS thesaurus manager).

**Comment by edgartdata** [comment]
@KraigBinkowski Would your collections have metadata to contribute to this facet?

**Comment by KraigBinkowski** [comment]
Yes, ref lib would have same 600 fields as rare, additionally, if we are thinking of the photo archives there are definitely many subjects that include sitters of portraits or family groups. The problem is that the T_Subject tables don't codify the type of subject so to isolate a person represented it would take two fields: the SUBJECT and the CATEGORY = "Portrait".

**Comment by flapka** [comment]
@edgartdata @KraigBinkowski Thinking aloud: Do we definitely want to exclude library material this is about a person (but without a portrait of the person)? I could see going either way.

The same question is pertinent to place represented.

**Comment by edgartdata** [comment]
@flapka The People Represented beading is actually misleading: it is rare but it happens that the art collections also uses this metadata element for people alluded to but not represented in, such as for William Shakespeare for whim of course there are  wet few portraits. 
However, 100% of the names of places linked to art collections that show up in the Places Repesented facet are actually visible in the works of art. 
That said I think both facets would be really powerful ways to connect the library and art collections.

**Comment by KraigBinkowski** [comment]
No, you're right, I would want to include lib materials about the person as well -- its just with the photo archive that the additional element of PORTRAIT would have to be added to not get hordes of unrelated results.

**Comment by edgartdata** [comment]
@yulgit1 replace the name of the People Represented facet with "Associated People"

**Comment by yulgit1** [comment]
@edgartdata On the show page there is the field 'People Represented or Subject' with the same data as the 'People Represented' facet.  Should both of these now be "Associated People"?

**Comment by edgartdata** [comment]
Do we want this facet to represent cases when a library item is about somebody rather than a visual representation of that person? April 23 discussion item.

**Comment by flapka** [comment]
@yulgit1 @edgartdata @KraigBinkowski 

Simple change: Map to People Represented from MARC 600 (all subfields).

(But MARC 600 should remain mapped to Subject Terms, too)

**Comment by yulgit1** [comment]
revised xslt for indexing this weekend: 600 (all subfields) to Associated People

https://git.yale.edu/ermadmix/ycba_xslts/commit/d26f7125337a5dfddf01276d802adf6810cc3697

**Comment by edgartdata** [comment]
@flapka Okay to close for RB?

**Comment by flapka** [comment]
@yulgit1 @edgartdata 

We could consider this resolved as is. Or: would it be better to eliminate the added subdivisions that appear after some names (e.g. "Bacon, Francis, 1909-1992 -- Exhibitions.")? Given the facet scope, I think it'd be better to omit such subdivisions. 

If you agree with my suggestion, then we should change the mapping (in this facet) to grab only 600 subfields abcdq. Sorry for not recognizing this earlier.

**Comment by yulgit1** [comment]
@edgartdata do you agree with Francis, (just 600 abcdq)?

**Comment by edgartdata** [comment]
@flapka yes, i think dropping the subdivisions (like --Exhibiitons) would be helpful here.

**Comment by edgartdata** [comment]
@yulgit1 the label in the New Additions facet would be: Past Year

**Comment by yulgit1** [comment]
@flapka 
600abcdq addressed in:
https://git.yale.edu/ermadmix/ycba_xslts/commit/7a2f1ceaf2c7d7b10e4c17d2a5a4418433cdaec8

to be reindexed...

**Comment by yulgit1** [comment]
@flapka how's Associated People look with this 600 abcdq only? OK to close?

**Comment by flapka** [comment]
Yes, very close. One small issue remains. Some headings include a terminal period, others don’t – depending on whether the mapping stripped away non-abcdq fields. See for example:

http://10.5.96.187:3000/?utf8=%E2%9C%93&f%5Bcollection_ss%5D%5B%5D=Rare+Books+and+Manuscripts&search_field=all_fields&q=reynolds

The heading for Joshua Reynolds appears twice, with and without the terminal period.

Is there a way to normalize and remove that period?

**Comment by yulgit1** [comment]
normalize by excluding trailing period addressed in: https://git.yale.edu/ermadmix/camel_collections2/commit/137664db7ace9469b7c34fa1c2416832b8f289b8

to be reindexed this weekend

**Comment by yulgit1** [comment]
@flapka - reindexed, Associated People facet look OK now?

**Comment by flapka** [comment]
Yes, looks good. Thanks!
